### ISSUE TITLE
Error in Tutorial

### ISSUE THREAD

**Issue by Palamir** [Jemsoft/monocular-demo-simple-face#1]
Thank you very much for the helpful tutorial. if has really helped me get started. However when i try and follow the facial recognition tutorial, and run the python code (on my windows computer) i get the following error.

`config.set('issued_at', datetime.now().strftime("%s"))`

ValueError: Invalid format string

I was wondering if that was a problem my set up, or with the code. I am running this on windows, plus i am in a different time zone to you. Was wondering if it was possible to help me you?

Kind Regards

**Comment by brandonjmatthews** [comment]
Hi, This appears to be a bug in the Python SDK, We have published a fixed version: 0.1.5
To update your SDK run: `pip install --upgrade monocular`

Please let us know if this has fixed your problem or if the problem continues so that we can investigate further.

**Comment by Palamir** [comment]
Thank you for the quick reply. Yes that solved the problem. Everything working fine now
